infrastructure-provisioning/src/general/conf/dlab.ini
infrastructure-provisioning/src/general/lib/os/debian/common_lib.py
infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py

Fixed the following tickets: [535] SSN creation fails and [540] Notebook creation (based on GPU) fails

Dlab 535 and 540 > v2.1-RC2

---

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py

[DLAB-535] Fixed instance creation issue due to missing -y flag and added condition to install linux-aws-hwe only on AWS

DLAB-535 > v.2.1-RC2

---

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py

[DLAB-535] Fixed instance creation issue due to missing -y flag and added condition to install linux-aws-hwe only on AWS

DLAB-535 > develop

---

infrastructure-provisioning/src/general/conf/dlab.ini
infrastructure-provisioning/src/general/files/aws/zeppelin_description.json
infrastructure-provisioning/src/general/files/azure/zeppelin_description.json
infrastructure-provisioning/src/general/files/gcp/zeppelin_description.json
integration-tests/examples/gcp_templates/deeplearning/dataproc.json
integration-tests/examples/gcp_templates/jupyter/dataproc.json
integration-tests/examples/gcp_templates/rstudio/dataproc.json
integration-tests/examples/gcp_templates/tensor/dataproc.json
integration-tests/examples/gcp_templates/zeppelin/dataproc.json

- update Zeppelin from 0.8.0 to 0.8.1 for Spark 2.4.0 support
- change autotest Dataproc version to 1.2 from 1.1

[DLAB-592] Upgrade Dataproc to 1.2 and 1.4 [bugfix]

---

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py
infrastructure-provisioning/src/general/scripts/aws/tensor-rstudio_configure.py

DLAB-1087 - [AWS]: RStudio with TensorFlow creation fails due to 'conf_service_base_name' is not defined fixed
DLAB-1084 - [Debian]: Notebook/spark cluster creations stuck using shared image

DLAB-1087 and DLAB-1084 fixes

---

infrastructure-provisioning/src/general/scripts/azure/edge_configure.py
infrastructure-provisioning/src/general/scripts/azure/project_prepare.py

[Azure] - outbound rules for edge security group updated (port 8080 for keycloak opened)

[DLAB-1363] - SSO on Azure fixed

---

infrastructure-provisioning/src/general/lib/os/fab.py

fixed failure of env termination and creation 
returned name of the function install_ungit

[DLAB-1570]: Rarely notebook creation fails on stage of 'npm' installation

---

infrastructure-provisioning/src/general/lib/gcp/actions_lib.py

fixed remote spark kernel removal for computational name that contains upper-case

[DLAB-1656]: [GCP][RStudio]: Remote kernel is still available in the list after Data Engine termination

---

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
infrastructure-provisioning/src/general/lib/os/fab.py
infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py

- If user installs already installed library but indicates fiction version, the output will be 'invalid version'
- If any distributive is not available for some library show as library installation 'Failed' and convey error message which we have previously
- If there is another error during installation except for 'No matching distribution found' show the status 'failed' and convey the particular error
- If library is failed convey which dependencies have been installed during installation  added dependencies to responce with failed status, probably some changes should be made on front-end to show dependency list with error message 
It's impossible to install any library from r package for Dataproc. **not ready yet**

[DLAB-1961]: Show error message if user tryes update/downgrade library by unreal  version

---

infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py

changed available yum package versions acquirement

[DLAB-2021]: For wrong library name convey 'invalid name' instead of 'invalid version' for Data Engine Service apt/yum group

---

infrastructure-provisioning/src/general/scripts/os/common_configure_spark.py

added check if /opt/{cluster_name} exist during custom spark creation

[DLAB-1980]: [Jupyter]: Custom Spark Standalone creation/reconfiguration fails 

---

infrastructure-provisioning/terraform/gcp/endpoint/main/variables.tf

added compute.routes.create, compute.routes.delete, compute.routes.get permissions for gcp external endpiont`s service account

[DLAB-2034]: Project creation fails for external endpoint on GCP

---

infrastructure-provisioning/src/project/scripts/configure_keycloak.py

added uuid import in configure keycloak

[DATALAB-2101]: [Azure][GCP]: Keycloak client should be created during project creation

---

infrastructure-provisioning/src/general/scripts/os/jupyterlab_container_start.py

[DATALAB-2119]: JupyterLab creation fails due to 'argparse' is not defined

---

infrastructure-provisioning/src/general/files/gcp/base_Dockerfile

specified qtconsole version in base dockerfile

[DATALAB-2168]: SSN deployment fails on step if downloading qtconsole

---

infrastructure-provisioning/src/jupyter/scripts/configure_jupyter_node.py

moved caTools version to datalab.ini for jupyter

[DATALAB-2190]: Notebook creation fails on stage of 'IRkernel' installation

---

infrastructure-provisioning/src/general/lib/os/debian/edge_lib.py

added installation of lua-resty-jwt v.0.2.2; latest 0.2.3 causes "unrecognised file extension error"

[DATALAB-2253]: fixed Edge creation fails on stage of luarocks installation

---

infrastructure-provisioning/src/general/files/gcp/base_Dockerfile

specified rsa version for gcp base image

[DATALAB-2292]: fixed SSN deployment fails on steps of 'rsa' downloading

---

infrastructure-provisioning/src/general/lib/aws/actions_lib.py

added in case if some policy that was not created during datalab deployment has been added to *-ssn-role. Otherwise ssn termination fails as it can not delete roles with attached policies

[DATALAB-2333]: added policies detachment from *-ssn-role

---

services/self-service/pom.xml

when I try to run command `mvn clean install -DskipTests -U` the Bintray repositories returning `Forbidden` response and there is information in Bintray the repositories will be sunset. when I try to run with maven central returning response
```
[ERROR] Failed to execute goal on project self-service: Could not resolve dependencies for project com.epam.datalab:self-service:jar:1.0: Could not find artifact com.novemberain:quartz-mongodb:jar:2.1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
So I change the repositories to Jitpack based on discussion on Github 
https://github.com/michaelklishin/quartz-mongodb/issues/217#issuecomment-861451719

[DATALAB-2413]-changed repository for mongo-quartz dependency

---

infrastructure-provisioning/src/general/scripts/os/update_inactivity_on_start.py

added check if disks are mounted right during notebook start on azure

[DATALAB-1838]: fixed Notebook/compute creation/starting fails

---

infrastructure-provisioning/src/general/conf/datalab.ini
infrastructure-provisioning/src/general/files/aws/deeplearning_description.json
infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
infrastructure-provisioning/src/general/scripts/aws/common_prepare_notebook.py
services/self-service/src/main/java/com/epam/datalab/backendapi/domain/NotebookTemplate.java
services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/ExploratoryServiceImpl.java

- aws deeplearning image version update
- primary ebs size raised to 150gb
- setuptools updated to 59.6.0
- nbformat downgraded to 5.1.3

[DATALAB-2813]: AWS Deeplearning Image Update

---

infrastructure-provisioning/terraform/bin/deploy/endpoint_fab.py
services/billing-aws/src/main/resources/application.yml
services/billing-azure/src/main/resources/application.yml
services/billing-gcp/src/main/resources/application.yml

Replaced configuration for realm for the AWS, Azure, and GCP clouds.

[DATALAB-2758]: Replaced hardcoded configuration for realm
