apache/incubator-datalab

infrastructure-provisioning/src/general/files/aws/dataengine_Dockerfile, infrastructure-provisioning/src/general/files/azure/dataengine_Dockerfile, infrastructure-provisioning/src/general/files/gcp/dataengine_Dockerfile, infrastructure-provisioning/src/general/scripts/aws/common_start_notebook.py, infrastructure-provisioning/src/general/scripts/aws/dataengine_start.py, infrastructure-provisioning/src/general/scripts/azure/common_start_notebook.py, infrastructure-provisioning/src/general/scripts/azure/dataengine_start.py, infrastructure-provisioning/src/general/scripts/gcp/common_start_notebook.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine_start.py, infrastructure-provisioning/src/general/scripts/os/notebook_inactivity_check.py, infrastructure-provisioning/src/general/scripts/os/update_inactivity_on_start.py, infrastructure-provisioning/src/general/templates/os/inactive.service, infrastructure-provisioning/src/general/templates/os/inactive.timer
[DLAB-405] Changes in names of idle_check parameters
=> [DLAB-402] Update last time inactivity after restarting by starting time

infrastructure-provisioning/src/general/files/gcp/ssn_roles.json
Assigned role to ssn service account that allow to use BigQuery API, ticket 529
=> EPMCDLAB-dev-529 > develop

infrastructure-provisioning/src/general/files/gcp/ssn_roles.json
[DLAB-529] Added Bigquery job User role
=> [DLAB-529] DLAB-dev-529 > develop

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
[DLAB-532] Fixed matplotlib downloading bug
=> Dlab-dev-532 > develop

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
=> [DLAB-475] Parametrise also keras r package same as python library

infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/lib/os/debian/common_lib.py, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
Fixed the following tickets: [535] SSN creation fails and [540] Notebook creation (based on GPU) fails
=> Dlab 535 and 540 > develop

infrastructure-provisioning/src/general/scripts/gcp/dataengine_prepare.py
Fixed dataengine creation issue due to missing GPU in spark cluster nodes
=> [DLAB-77] Fixed dataengine creation issue

infrastructure-provisioning/src/dataengine/scripts/configure_dataengine.py, infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
-remove old and unsupported library Caffe
-change versionc of cuda for Data Engine on deeplearning
=> [GCP]: Fix Data Engine creation fails on DeepLearning

infrastructure-provisioning/src/edge/fabfile.py, infrastructure-provisioning/src/general/lib/os/debian/edge_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/edge_lib.py, infrastructure-provisioning/src/general/scripts/aws/project_prepare.py, infrastructure-provisioning/src/general/scripts/aws/ssn_configure.py, infrastructure-provisioning/src/general/scripts/gcp/project_prepare.py, infrastructure-provisioning/src/general/scripts/gcp/ssn_configure.py, infrastructure-provisioning/src/project/scripts/configure_nginx_reverse_proxy.py, infrastructure-provisioning/src/project/templates/nginx.conf
Notebook creation fixes
Project tag added to bucket
=> Dlab 748 Project creation (Notebook creation fixes)

infrastructure-provisioning/terraform/bin/terraform-cli.py
=> Add auto-approve

infrastructure-provisioning/terraform/bin/terraform-cli.py
=> Add k8s cluster status check

infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/scripts/aws/common_notebook_configure_dataengine.py
Spark cluster configuration fails fixed
EMR configuration fails fixed
=> Dlab 748 - EMR and Spark cluster configuration fails fixed

infrastructure-provisioning/src/edge/fabfile.py, infrastructure-provisioning/src/general/api/status.py, infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_create.py, infrastructure-provisioning/src/general/scripts/aws/dataengine_prepare.py, infrastructure-provisioning/src/general/scripts/aws/edge_status.py
Spark cluster and EMR cluster project tag added
Docker of resource status fixed
IAM role project tag added
=> DLAB-748 (project tags and bug fixes)

infrastructure-provisioning/src/general/lib/aws/actions_lib.py
=> DLAB-748 IAM Role creation fixed

infrastructure-provisioning/src/general/scripts/aws/project_prepare.py, infrastructure-provisioning/src/general/scripts/aws/project_terminate.py
Modified attachment project tags to Endpoints.
=> Modified attachment project tags to Endpoints.

infrastructure-provisioning/src/general/scripts/aws/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/aws/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/aws/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/aws/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/tensor-rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/tensor_configure.py, infrastructure-provisioning/src/general/scripts/aws/zeppelin_configure.py
Shared AMI creating and using per project and per endpoint.
=> [DLAB-962] Shared AMI creating and using per project and per endpoint.

infrastructure-provisioning/src/base/scripts/install_user_key.py
Project public key is absent on notebooks and computational resources fixed
=> DLAB-970 - Project public key issue resolved

infrastructure-provisioning/src/general/files/gcp/base_Dockerfile, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_configure.py
[GCP]: Dataproc creation fails issue resolved
=> Dlab 748 [GCP]: Dataproc creation fails

infrastructure-provisioning/src/general/scripts/aws/dataengine_configure.py, infrastructure-provisioning/src/general/scripts/gcp/common_notebook_configure_dataengine-service.py, infrastructure-provisioning/src/general/scripts/gcp/common_notebook_configure_dataengine.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine_configure.py
[GCP]: Custom spark cluster creation fails resolved
[GCP]: Dataproc creation fails resolved
Project public key is absent on notebooks and computational resources resolved
=> Dlab 748 - computational resources creation fixed

infrastructure-provisioning/src/general/scripts/aws/dataengine_prepare.py
[AWS] Data Engine should use notebooks's AMI during cration solved
=> DLAB-983 Data Engine creation from AMI

infrastructure-provisioning/terraform/aws/endpoint/main/network.tf, infrastructure-provisioning/terraform/aws/endpoint/main/variables.tf
Changed subnet_id to ssn_subnet.
=> Changed subnet_id to ssn_subnet.

infrastructure-provisioning/src/general/scripts/aws/project_terminate.py, infrastructure-provisioning/src/general/scripts/azure/edge_configure.py, infrastructure-provisioning/src/general/scripts/azure/project_prepare.py
[Azure] Project creation fixed
[AWS ] Project terminate fixed
=> DLAB-748 - Azure project creation fixes

infrastructure-provisioning/src/general/files/azure/project_Dockerfile, infrastructure-provisioning/src/general/lib/azure/actions_lib.py, infrastructure-provisioning/src/general/scripts/aws/ssn_prepare.py, infrastructure-provisioning/src/general/scripts/azure/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/azure/edge_stop.py
[AWS] Limit SBN length implemented
[Azure] Project creation fixed
[Azure] Project stop fixed
[Azure] Notebook creation fixed
=> Dlab 748 - Notebook creation fixed (azure)

infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_terminate.py
[GCP]: Dataproc termination fails
=> DLAB-982 - Dataproc termination fails fixed

infrastructure-provisioning/src/general/lib/gcp/actions_lib.py, infrastructure-provisioning/src/general/scripts/gcp/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/gcp/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/gcp/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/gcp/tensor-rstudio_configure.py, infrastructure-provisioning/src/general/scripts/gcp/tensor_configure.py, infrastructure-provisioning/src/general/scripts/gcp/zeppelin_configure.py
[GCP]: Add endpoint_tag and project_tag for images
=> DLAB-1002 - [GCP]: Add endpoint_tag and project_tag for images

infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_create.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_create.py, infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py
[GCP]: project termination fixed
[AWS]: Add endpoint_tag for SG for EMR
[GCP]: Dataproc creation fixed
=> [GCP]: Dataproc creation fixed

infrastructure-provisioning/terraform/aws/endpoint/main/instance.tf
Added "endpoint_id" tag for ec2.
=> Added "endpoint_id" tag for ec2.

infrastructure-provisioning/src/general/scripts/aws/ssn_prepare.py, infrastructure-provisioning/src/general/scripts/azure/ssn_prepare.py, infrastructure-provisioning/src/general/scripts/gcp/edge_terminate.py, infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py, infrastructure-provisioning/src/general/scripts/gcp/ssn_prepare.py, infrastructure-provisioning/src/general/scripts/gcp/ssn_terminate_gcp_resources.py, services/security-service/security.yml
[AWS] SBN unique validation added 
[Azure] SBN unique validation added 
[GCP] SBN unique validation added 
[GCP] Service accounts and roles removing prevented for similar SBN
=> Dlab 748 - unique SBN check implemented

infrastructure-provisioning/src/general/scripts/aws/common_create_security_group.py, infrastructure-provisioning/src/general/scripts/aws/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py, infrastructure-provisioning/src/general/scripts/aws/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/aws/edge_configure.py, infrastructure-provisioning/src/general/scripts/aws/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/aws/project_prepare.py, infrastructure-provisioning/src/general/scripts/aws/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/ssn_configure.py, infrastructure-provisioning/src/general/scripts/aws/ssn_prepare.py, infrastructure-provisioning/src/general/scripts/aws/tensor-rstudio_configure.py, infrastructure-provisioning/src/general/scripts/aws/tensor_configure.py, infrastructure-provisioning/src/general/scripts/aws/zeppelin_configure.py
[AWS] 'sg' in security_group_name in lower case fixed
=> DLAB-996 - [AWS] 'sg' in security_group_name in lower case fixed

infrastructure-provisioning/src/general/scripts/aws/common_create_notebook_image.py
[DLAB-1035] Fixed custom images using.
=> [DLAB-1035] Fixed custom images using.

infrastructure-provisioning/src/general/scripts/azure/edge_configure.py
[Azure]: Project status is not updated from creating to active fixed
=> DLAB-1050 - Project status is not updated from creating to active fixed

infrastructure-provisioning/src/general/scripts/gcp/dataengine_start.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine_stop.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine_terminate.py
[DLAB-1073][GCP] Failed spark start, stop or terminate procedure in case of uppercase in project name.
=> [DLAB-1073][GCP] Failed spark start, stop or terminate procedure in case of uppercase in project name.

services/self-service/src/main/resources/webapp/src/app/administration/roles/roles.component.scss, services/self-service/src/main/resources/webapp/src/app/administration/roles/roles.component.ts, services/self-service/src/main/resources/webapp/src/app/core/util/checkUtils.ts, services/self-service/src/main/resources/webapp/src/app/core/util/patterns.ts, services/self-service/src/main/resources/webapp/src/app/resources/computational/computational-resource-create-dialog/computational-resource-create-dialog.component.ts, services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.scss
[DLAB-1069]: changed validation on roles management;
[DLAB-1072]: fixed extra expansion of the library list;
=> [DLAB-1070][DLAB-1051]: fixed notebook and clusters validation on the identity

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py
Hot-fix. Fixing exit after 60 tries.
=> Hot-fix. Fixing exit after 60 tries.

infrastructure-provisioning/src/general/files/gcp/tensor-rstudio_description.json
Temporarily removed tensor-rstudio template because of unpreparedness
=> [DLAB-77] Temporarily removed tensor-rstudio template

infrastructure-provisioning/src/general/scripts/azure/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/azure/dataengine_prepare.py, infrastructure-provisioning/src/general/scripts/azure/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/azure/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/azure/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/azure/tensor_configure.py, infrastructure-provisioning/src/general/scripts/azure/zeppelin_configure.py
[Azure]: Shared AMis for both per project and per endpoint
[Azure]: Any notebook is not created successfully fixed
=> [DLAB-748]: Any notebook is not created successfully in Azure fixed

services/self-service/src/main/java/com/epam/dlab/backendapi/dao/SchedulerJobDAO.java
- Fixed bug with scheduler by inactivity.
=> [DLAB-1081]: Fixed bug with scheduler by inactivity

infrastructure-provisioning/terraform/gcp/endpoint/daemon.json, infrastructure-provisioning/terraform/gcp/endpoint/main/iam.tf, infrastructure-provisioning/terraform/gcp/endpoint/main/instance.tf, infrastructure-provisioning/terraform/gcp/endpoint/main/main.tf, infrastructure-provisioning/terraform/gcp/endpoint/main/network.tf, infrastructure-provisioning/terraform/gcp/endpoint/main/variables.tf, infrastructure-provisioning/terraform/gcp/endpoint/provisioning.py, infrastructure-provisioning/terraform/gcp/endpoint/provisioning.yml, infrastructure-provisioning/terraform/gcp/endpoint/supervisor_svc.conf
infrastructure-provisioning/terraform/gcp/endpoint
=> Added Endpoint for GCP by

infrastructure-provisioning/src/general/lib/gcp/actions_lib.py, infrastructure-provisioning/src/general/lib/os/debian/ssn_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/ssn_lib.py
Hotfix for ssn creation on other clouds.
=> Fixed name of GCP dataproc.

services/self-service/src/main/java/com/epam/dlab/backendapi/resources/ProjectResource.java, services/self-service/src/main/java/com/epam/dlab/backendapi/resources/dto/KeysDTO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/AccessKeyService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/AccessKeyServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/resources/ProjectResourceTest.java
- Added _POST_ endpoint to generate key pairs [publicKey, privateKey] - _api/project/keys_.
=> [DLAB-1078]:  Added endpoint to generate key pairs

infrastructure-provisioning/terraform/gcp/endpoint/daemon.json, infrastructure-provisioning/terraform/gcp/endpoint/main/instance.tf, infrastructure-provisioning/terraform/gcp/endpoint/main/network.tf, infrastructure-provisioning/terraform/gcp/endpoint/main/variables.tf, infrastructure-provisioning/terraform/gcp/endpoint/provisioning.py, infrastructure-provisioning/terraform/gcp/endpoint/provisioning.yml
Added new changes to endpoint for GCP, than was stored locally before
=> Added new changes to endpoint for GCP.

services/self-service/src/main/java/com/epam/dlab/backendapi/resources/KeycloakResource.java
=> [DLAB-1018]:  Added possibility to logout

services/dlab-model/src/main/java/com/epam/dlab/model/exploratory/Image.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/ImageExploratoryDao.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/ImageExploratoryDaoImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/resources/ImageExploratoryResource.java, services/self-service/src/main/java/com/epam/dlab/backendapi/resources/dto/ImageInfoRecord.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/ImageExploratoryService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/ImageExploratoryServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/resources/ImageExploratoryResourceTest.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/ImageExploratoryServiceImplTest.java
- Added possibility to retrieve custom images per endpoint
=> [DLAB-1054]: Added possibility to retrieve custom images per endpoint

infrastructure-provisioning/terraform/bin/deploy/endpoint_fab.py
Temporary fix for provisioning of Endpoint (alb and nlb added again).
=> Temporary fix for provisioning of Endpoint (alb and nlb added again).

services/billing-gcp/src/main/java/com/epam/dlab/billing/gcp/service/BillingServiceImpl.java, services/billing-gcp/src/main/java/com/epam/dlab/billing/gcp/util/BillingUtils.java
=> [DLAB-1123]: Fixed billing issues

services/self-service/src/main/java/com/epam/dlab/backendapi/resources/KeycloakResource.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/KeycloakServiceImpl.java
- Added possibility to use multiple keycloak redirecturi
=> Added possibility to use multiple keycloak redirecturi

services/self-service/src/main/java/com/epam/dlab/backendapi/dao/SecurityDAO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/resources/KeycloakResource.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/KeycloakService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/KeycloakServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/KeycloakServiceImplTest.java
- Update user in mongo while refreshing access token
=> [DLAB-1156] Update user in mongo while refreshing access token

services/dlab-model/src/main/java/com/epam/dlab/model/scheduler/SchedulerJobData.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/ComputationalDAO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/SchedulerJobDAO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/schedulers/CheckProjectQuoteScheduler.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/KeycloakService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/KeycloakServiceImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/SecurityService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/SecurityServiceImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/EnvironmentServiceImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/resources/SchedulerJobResourceTest.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/EnvironmentServiceImplTest.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImplTest.java
- Fixed scheduler issue with token expiration
=> [DLAB-1201] Fixed scheduler issue with token expiration

infrastructure-provisioning/src/general/scripts/aws/project_prepare.py
fixed endpoint name for bucket creation
=> fixed endpoint name for right bucket creation

services/self-service/src/main/java/com/epam/dlab/backendapi/util/RequestBuilder.java
- Fixed bug with reconfiguration spark on Notebook [Azure]
=> [DLAB-1224] Fixed bug with reconfiguration spark on Notebook [Azure]

services/dlab-model/src/main/java/com/epam/dlab/dto/exploratory/ExploratoryBaseDTO.java
- Fixed bug with notebook stopping [AWS]
=> [DLAB-1226] Fixed bug with notebook stopping [AWS]

services/self-service/src/main/java/com/epam/dlab/backendapi/dao/ProjectDAOImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/ProjectServiceImpl.java
- Fixed bug with  group while creating resource
=> [DLAB-1228] Fixed bug with  group while creating resource

services/dlab-model/src/main/java/com/epam/dlab/dto/aws/AwsCloudSettings.java, services/dlab-model/src/main/java/com/epam/dlab/dto/azure/AzureCloudSettings.java, services/dlab-model/src/main/java/com/epam/dlab/dto/gcp/GcpCloudSettings.java, services/provisioning-service/provisioning.yml, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/CloudConfiguration.java, services/provisioning-service/src/main/java/com/epam/dlab/backendapi/core/commands/CommandBuilder.java
Added new cloud parameters in provisioning
=> [DLAB-1220] Added new cloud parameters in provisioning

infrastructure-provisioning/scripts/deploy_repository/deploy_repository.py, infrastructure-provisioning/src/general/lib/aws/actions_lib.py
=> [DLAB-1232] Temporary removed jar, which is missing in official maven repo

infrastructure-provisioning/src/general/lib/gcp/actions_lib.py, infrastructure-provisioning/src/general/scripts/gcp/common_create_bucket.py
added label 'name:{sbn}-{project_name}-{endpoint_name}-bucket' to gcp buckets
=> [DLAB-1128]

services/self-service/src/main/java/com/epam/dlab/backendapi/schedulers/CheckUserQuoteScheduler.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/EnvironmentService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/SecurityService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/SecurityServiceImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/EnvironmentServiceImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/schedulers/CheckUserQuoteSchedulerTest.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/EnvironmentServiceImplTest.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImplTest.java
- Using **getUserInfoOffline** instead of **getServiceAccountInfo** while stopping notebook via dlab UI.
=> [DLAB-1256] Fixed issue with stopping notebook

infrastructure-provisioning/src/general/scripts/gcp/ssn_terminate.py
added global parameter pre_defined_vpc for 'gcp ssn_terminate = false'
=> added global parameter pre_defined_vpc for gcp ssn_terminate

infrastructure-provisioning/src/general/scripts/gcp/ssn_terminate.py
added lowercase replacement for SBN gcp ssn_terminate
=> added lowercase replacement for SBN gcp ssn_terminate

services/self-service/src/main/java/com/epam/dlab/backendapi/dao/ImageExploratoryDao.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/ImageExploratoryDaoImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/resources/ImageExploratoryResource.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/ImageExploratoryService.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/ImageExploratoryServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/resources/ImageExploratoryResourceTest.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/ImageExploratoryServiceImplTest.java
- Check whether there is such an image in the project while creating image;
- Added endpoint to disable apply button on UI.
=> [DLAB-1261] Custom image is unique per project

infrastructure-provisioning/src/general/lib/aws/actions_lib.py
Added sbn tag to images and snapshots so they could be deleted during SSN termination
=> [DLAB-1269] Added sbn tag to images and snapshots

infrastructure-provisioning/src/general/scripts/azure/common_notebook_configure_dataengine.py
[Azure] Reconfiguration spark on Data Engine fails fixed
=> [DLAB-1177] Reconfiguration spark on Data Engine fails fixed

services/self-service/src/main/resources/webapp/src/app/resources/exploratory/detail-dialog/detail-dialog.component.html, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.scss
=> [DLAB-1248] Fixed bottom header line is not drawn for all grid on FireFox

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
[DLAB-1327] - Jupyter/DeepLearnin/TensorFlow creation fails fixed (ipython version 7.9.0 hardcoded)
=> [DLAB-1327] - Jupyter/DeepLearnin/TensorFlow creation fails fixed

services/self-service/src/main/resources/webapp/src/app/administration/project/project.component.ts, services/self-service/src/main/resources/webapp/src/app/shared/modal-dialog/notification-dialog/notification-dialog.component.ts, services/self-service/src/main/resources/webapp/src/assets/styles/_variables.scss, services/self-service/src/main/resources/webapp/src/styles.scss
=> [DLAB-1358]: adjusted confirmation messages for edge node on projects list

infrastructure-provisioning/src/project/templates/nginx.conf
[DLAB-1363] - SSO on AWS fixed - worker_processes at nginx set for 1
=> [DLAB-1363] - SSO on AWS fixed

infrastructure-provisioning/src/general/lib/gcp/meta_lib.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_prepare.py
[GCP] Simultaneously Data Engine Service creation fixed
=> [DLAB-1404] - [GCP] Simultaneously Data Engine Service creation fixed

infrastructure-provisioning/src/general/scripts/aws/jupyter_dataengine-service_create_configs.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_jars_parser.py, infrastructure-provisioning/src/general/scripts/gcp/jupyter_dataengine-service_create_configs.py, infrastructure-provisioning/src/general/scripts/gcp/jupyter_install_dataengine-service_kernels.py, infrastructure-provisioning/src/general/scripts/os/jupyter_dataengine_create_configs.py
[DLAB-1409] -Scala version is not actual on Jupyter UI for DES/Jupyter fixed
=> [DLAB-1409] - Scala version is actual on Jupyter UI for DES/Jupyter

README.md
documentation for existing Keycloak in README.md added
=> [DLAB-1452]: documentation for existing Keycloak in README.md added

infrastructure-provisioning/src/general/lib/os/debian/ssn_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/ssn_lib.py, infrastructure-provisioning/src/general/templates/os/manage_step_certs.sh, infrastructure-provisioning/src/general/templates/os/renew_certificates.sh, infrastructure-provisioning/src/project/templates/conf.d/proxy.conf, infrastructure-provisioning/src/ssn/scripts/configure_ssn_node.py, infrastructure-provisioning/src/ssn/templates/nginx_proxy.conf, infrastructure-provisioning/terraform/bin/deploy/endpoint_fab.py, infrastructure-provisioning/terraform/bin/deploy/manage_step_certs.sh, infrastructure-provisioning/terraform/bin/deploy/renew_certificates.sh, services/self-service/entrypoint.sh
Fixed issue with SSN_INSTANCE_SIZE parameter;
Fixed issue with Nginx configuration;
Fixed issue with Step certificates;
=> [DLAB-1462]: Fixed issue with SSN_INSTANCE_SIZE parameter

infrastructure-provisioning/src/general/scripts/azure/ssn_configure.py
=> [DLAB-1487]: [Azure] Shared endpoint bucket should be created during project creation hot bugs fixes

README.md, infrastructure-provisioning/scripts/deploy_keycloak/deploy_keycloak.py, infrastructure-provisioning/scripts/deploy_keycloak/templates/keycloak.service, infrastructure-provisioning/scripts/deploy_keycloak/templates/nginx.conf, infrastructure-provisioning/scripts/deploy_keycloak/templates/realm.json
Created Keycloak and Nginx installation script
=> [DLAB-1449] Create Keycloak installation script

infrastructure-provisioning/src/general/scripts/azure/project_prepare.py
fixed [Azure] Project creation fails
=> [DLAB-1508]: [Azure] Project creation fails

infrastructure-provisioning/src/general/scripts/azure/edge_configure.py, infrastructure-provisioning/src/general/scripts/azure/project_prepare.py
Added endpoint name to container and shared container names
=> [DLAB-1532] Added endpoint name to container and shared container names

infrastructure-provisioning/src/general/scripts/azure/project_prepare.py
[Azure] fixed project creation fails
=> [DLAB-1538]: [Azure] fixed project creation fails

infrastructure-provisioning/src/general/scripts/aws/dataengine-service_configure.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py
=> [DLAB-1530]: Added Endpoint_tag for EMR

infrastructure-provisioning/src/general/scripts/azure/edge_configure.py, infrastructure-provisioning/src/general/scripts/azure/edge_prepare.py
added endpoint name to user container name that is written to result.json
=> [DLAB-1532]: added endpoint name to user container name that is written to result.json

infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py
=> [DLAB-1547]: fixed error with emr creation

infrastructure-provisioning/src/general/scripts/azure/project_prepare.py
Project creation is successful
azure storage account has both Name and "SBN"-tag tags
=> [DLAB-1581]: [Azure]: Project creation fails on stage of shared storage account/container creation

README.md, infrastructure-provisioning/scripts/deploy_dlab.py, infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/scripts/aws/ssn_configure.py, infrastructure-provisioning/src/general/scripts/azure/ssn_configure.py, infrastructure-provisioning/src/general/scripts/gcp/ssn_configure.py
commented in dlab.ini as this parameter is being get from the UI
=> [DLAB-1468]: Remove parameter sharedImageEnabled from configuration files

infrastructure-provisioning/terraform/azure/endpoint/main/instance.tf, infrastructure-provisioning/terraform/azure/endpoint/main/main.tf, infrastructure-provisioning/terraform/azure/endpoint/main/network.tf
remote endpoint creation is successful
=> [DLAB-1595]: [Azure]: Remote endpoint creation fails

infrastructure-provisioning/src/general/lib/gcp/meta_lib.py, infrastructure-provisioning/src/general/scripts/gcp/common_notebook_configure_dataengine-service.py, infrastructure-provisioning/src/general/scripts/gcp/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_prepare.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine_prepare.py
user tag now has correct value, also added custom tag for notebook and dataengine
=> [DLAB-1539]: [GCP]: Value of user_tag should contain username but not random generated value

infrastructure-provisioning/src/general/scripts/gcp/common_notebook_configure_dataengine-service.py, infrastructure-provisioning/src/general/scripts/gcp/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_prepare.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine_prepare.py
fixed Notebook creation fails if project name contains upper case
=> [DLAB-1612]: [GCP]: Notebook creation fails if project name contains upper case

infrastructure-provisioning/src/general/scripts/gcp/deeplearning_configure.py, infrastructure-provisioning/src/general/scripts/gcp/jupyter_configure.py, infrastructure-provisioning/src/general/scripts/gcp/jupyterlab_configure.py, infrastructure-provisioning/src/general/scripts/gcp/rstudio_configure.py, infrastructure-provisioning/src/general/scripts/gcp/superset_configure.py, infrastructure-provisioning/src/general/scripts/gcp/tensor-rstudio_configure.py, infrastructure-provisioning/src/general/scripts/gcp/tensor_configure.py, infrastructure-provisioning/src/general/scripts/gcp/zeppelin_configure.py
fixed notebook and spark cluster creation
=> [DLAB-1627]: Notebook creation fails from image

infrastructure-provisioning/src/general/scripts/aws/common_create_notebook_image.py
custom image created successfully
=> [DLAB-1631]: Custom image creation fails on remote AWS endpoint	

infrastructure-provisioning/src/general/scripts/aws/edge_configure.py
made project bucket name contain lower-case to FE
=> [DLAB-1630]: Project bucket name should be contain lower-case to FE

infrastructure-provisioning/src/general/scripts/aws/common_notebook_configure_dataengine-service.py, infrastructure-provisioning/src/general/scripts/aws/common_stop_notebook.py, infrastructure-provisioning/src/general/scripts/aws/common_terminate_notebook.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_configure.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_terminate.py, infrastructure-provisioning/src/general/scripts/aws/edge_configure.py
fixed Data Engine Service creation fails if project name contains upper case
=> [DLAB-1628]: [AWS]: Data Engine Service creation fails if project name contains upper case

infrastructure-provisioning/src/general/scripts/gcp/common_stop_notebook.py
=> [DLAB-1624]: [GCP]: Notebook stopping fails on remote GCP endpoint	

infrastructure-provisioning/src/general/scripts/gcp/edge_start.py
fixed Edge node starting fails
=> [DLAB-1625]: [GCP]: Edge node starting fails on remote GCP endpoint

infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py
imaged that start with service_base_name-project_name are deleted during project termination
=> [DLAB-1642]: [GCP]: Images are not deleted after project termination

infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py
fixed Service accounts are not deleted after project termination
=> [DLAB-1643]: [GCP]: Service accounts are not deleted after project termination

infrastructure-provisioning/src/project/scripts/configure_keycloak.py
=> [DLAB-1641]: Unable to go instance link if KeyCloak client contains upper case for remote endpoint

infrastructure-provisioning/src/general/scripts/aws/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/azure/common_prepare_notebook.py
fixed notebook creation from custom image does not use custom image
=> [DLAB-1657]: Notebook creation from custom image does not use custom image

infrastructure-provisioning/src/general/scripts/azure/edge_configure.py
=> [DLAB-1666]: [Azure]: Convey project bucket account to FE

infrastructure-provisioning/src/general/scripts/azure/edge_configure.py
=> [DLAB-1668]: [Azure]: Convey container name in lower case to FE

infrastructure-provisioning/src/general/scripts/aws/project_terminate.py, infrastructure-provisioning/src/general/scripts/azure/project_terminate.py
added images removal during project termination
=> [DLAB-1665]: [AWS][Azure]: Images are not deleted after project termination

infrastructure-provisioning/src/general/files/aws/deeplearning_description.json, infrastructure-provisioning/src/general/files/azure/deeplearning_description.json, infrastructure-provisioning/src/general/files/azure/tensor_description.json, infrastructure-provisioning/src/general/files/gcp/deeplearning_description.json
[DLAB-1729]: [Azure] Name for 'Jupyter with TensorFlow 1.8.0' is alike for all cloud
[DLAB-1730]: Name of template 'Deep Learning 2.3' updated
=> [DLAB-1729]: [Azure] Name for 'Jupyter with TensorFlow 1.8.0' is alike for all cloud

infrastructure-provisioning/src/general/scripts/gcp/common_prepare_notebook.py
increased primary disk size to 14G as with 12G tensorflow with jupyter creation failed
=> [DLAB-1827]: fixed TensorFlow with Jupyter creation fails

infrastructure-provisioning/src/general/scripts/gcp/common_create_notebook_image.py, infrastructure-provisioning/src/general/scripts/gcp/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/gcp/common_terminate_notebook_image.py, services/provisioning-service/src/main/resources/mock_response/gcp/notebook_create_image.json, services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.html
added custom images creation and usage
=> [DLAB-54]: Add custom images

infrastructure-provisioning/src/general/scripts/gcp/common_create_notebook_image.py, infrastructure-provisioning/src/general/scripts/gcp/common_prepare_notebook.py, infrastructure-provisioning/src/general/scripts/gcp/common_terminate_notebook_image.py
fixed Custom image creation fails if image name contains upper case
=> [DLAB-1882]: fixed Custom image creation fails if image name contains upper case

infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_configure.py
Library installation is now successful
=> [DLAB-1855]: [Branch-515][AWS]: fixed Library installation fails from python packages on EMR

infrastructure-provisioning/src/general/scripts/aws/project_terminate.py, infrastructure-provisioning/src/general/scripts/azure/project_terminate.py, infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py
fixed Edge termination deletes image of another endpoint within one project
=> [DLAB-1940]: Edge termination deletes image of another endpoint within one project

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
now docker will run with 0 and return statuses for libs
=> [DLAB-1962]: If docker runs with '1' the library status is stuck in 'installing' in Web UI

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py, infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/AccessKeyServiceImplTest.java
fixed for both EMR and Dataproc
Library from APT/YUM is installed
Library from r package is installed
Do not convey lib_name in dependency (htop from 'Apt/Yum' group)
Do not convey <***> in 'Version is not available' (vlan/wget from 'Apt/Yum' group)
=> [DLAB-1966]: Lib installation fails from r/Apt/Yum packages for Data Engine Service

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
=> [DLAB-1983]: Convey 'invalid name' status if it is tryout to install lib with wrong name

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
specified opencv-python version for pip2
=> [DLAB-1988]: TensorFlow with Jupyter creation fails on stage of opencv-python lib install

infrastructure-provisioning/src/general/files/aws/deeplearning_description.json, infrastructure-provisioning/src/general/files/aws/tensor-rstudio_description.json, infrastructure-provisioning/src/general/files/aws/tensor_description.json
changed tensorflow and deeplearning versions in description
=> [DLAB-1994]: [TensorFlow][DeepLearning]: Convey new version to UI

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py
fixed Issues if install library with unfound version
=> [DLAB-1996]: Issues if install library with unfound version

infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py
fixed yum package installation error for EMR, pip issue was fixed in scope of DLAB-1996
=> [DLAB-1997]: Issues if installed library with unknown name

infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/lib/azure/actions_lib.py, infrastructure-provisioning/src/general/lib/gcp/actions_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_create.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py, infrastructure-provisioning/src/general/scripts/os/jupyter_install_dataengine_kernels.py
[DLAB-1979] - Deep Learning creation fixed
=> [DLAB-1985] - Got rid of previous logic for allocation of Spark executor memory

infrastructure-provisioning/src/general/lib/azure/actions_lib.py
added retries in case of failure during disk prepare
=> [DLAB-1864]: [Branch-515][Azure]: Notebook creation fail on disk mount

infrastructure-provisioning/src/general/scripts/aws/jupyterlab_configure.py, infrastructure-provisioning/src/general/scripts/gcp/jupyterlab_configure.py
fixed AMI creation for jupyterlab
=> [DLAB-2018]: JupyterLab image is not created during the first notebook creation

infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/lib/azure/actions_lib.py, infrastructure-provisioning/src/general/lib/gcp/actions_lib.py, infrastructure-provisioning/src/general/scripts/os/dataengine_reconfigure_spark.py
=> [DLAB-1980]: [Jupyter]: Custom Spark Standalone creation/reconfiguration fails

services/self-service/src/test/java/com/epam/dlab/backendapi/resources/ProjectResourceTest.java
- getProject and getProjects tests have been added
=> [DLAB] Project resource UT

services/self-service/src/test/java/com/epam/dlab/backendapi/resources/ProjectResourceTest.java
=> [DLAB ]Project resource UT

infrastructure-provisioning/src/general/lib/os/fab.py
=> [DLAB-2037]: [Jupyter][Jupyter with TensorFlow][DeepLearning]: Notebook creation fails on stage of 'pyrsistent' download

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py
change manage_pkg function to fix dpkg frontend locker error
=> [DLAB-1527]: Rarely notebook is not created successful from the first attempt or ssn

infrastructure-provisioning/src/general/files/aws/rstudio_description.json, infrastructure-provisioning/src/general/files/azure/rstudio_description.json, infrastructure-provisioning/src/general/files/gcp/rstudio_description.json, services/self-service/src/main/java/com/epam/dlab/backendapi/domain/NotebookTemplate.java
changed Rstudio version in description json
=> [DLAB-2025]: changed Rstudio version in description json

CONTRIBUTING.md, infrastructure-provisioning/src/general/conf/dlab.ini, infrastructure-provisioning/src/general/files/aws/rstudio_description.json, infrastructure-provisioning/src/general/files/azure/rstudio_description.json, infrastructure-provisioning/src/general/files/gcp/rstudio_description.json, services/self-service/src/main/java/com/epam/dlab/backendapi/domain/NotebookTemplate.java
Downgraded RStudio to the previous version
=> [DLAB-2052]: Downgraded RStudio to the previous version

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
fixed link and rstudio service path
=> [DLAB-2052]: Downgrade RStudio to the previous version

services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/SchedulerJobServiceImpl.java
Fixed bug with a reminder about notebook stopping continues to show up after scheduler triggering
=> [DLAB-1922] Fixed bug with reminder about notebook stopping

infrastructure-provisioning/src/general/scripts/azure/ssn_terminate.py, infrastructure-provisioning/src/general/scripts/gcp/ssn_terminate_gcp_resources.py
fixed some bugs during env termination with predefined vpc, subnet, etc. for gcp and azure
=> [DLAB-1911]: Support access to all existing and following environments only via VPN

infrastructure-provisioning/src/general/scripts/azure/ssn_configure.py, infrastructure-provisioning/src/general/scripts/azure/ssn_prepare.py
=> [DATALAB-2076]: [Azure]: SSN creation fails

infrastructure-provisioning/src/ssn/scripts/configure_ui.py
=> [DATALAB-2095]: [GCP]: SSN deployment fails on stage of mongo configuration

services/self-service/src/main/java/com/epam/dlab/backendapi/dao/OdahuDAO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/dao/OdahuDAOImpl.java, services/self-service/src/main/java/com/epam/dlab/backendapi/domain/OdahuFieldsDTO.java, services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/OdahuServiceImpl.java
it's possible to add ODAHU cluster, if there are no Stopped or Active Instances
=> [DLAB-1650] Creating ODAHU cluster in same project

infrastructure-provisioning/src/general/files/gcp/ssn_policy.json, infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py
added route removal during project termination and added required permissions for ssn
=> [DATALAB-2106]: [GCP]: Not all resources are terminated after endpoint disconnection

infrastructure-provisioning/src/general/scripts/gcp/project_terminate.py
added check if nat route exists before its removal
=> [DATALAB-2120]: Add extra validation for existing nat route during termination

infrastructure-provisioning/src/general/scripts/gcp/ssn_terminate_gcp_resources.py
changed call of GCPActions and GCPMeta
=> [DATALAB-2118]: [GCP]: SSN termination fails if Dataproc is in running status

infrastructure-provisioning/src/general/scripts/gcp/project_prepare.py
added another vpc subnet cidr as allowed source range for edge-sg-ingress-internal firewall
=> [DATALAB-2131]: [GCP]: Jupyterlab creation fails on stage of connection configuration

README.md
https://issues.apache.org/jira/browse/DATALAB-2153
Fixed wrong path to dir
Updated info about conf file
Updated info about creation configuration
=> [Datalab-2153] updated Readme (setup section)

services/self-service/src/main/java/com/epam/dlab/backendapi/service/impl/OdahuServiceImpl.java, services/self-service/src/test/java/com/epam/dlab/backendapi/service/impl/OdahuServiceImplTest.java
=> [DLAB-2116] Oduhu unitests

infrastructure-provisioning/src/general/scripts/aws/dataengine-service_prepare.py
changed how rules for emr additional security group are created
=> [DATALAB-2154]: EMR creation fails

README.md, services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/EndpointServiceImpl.java, services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/ProjectServiceImpl.java, services/self-service/src/test/java/com/epam/datalab/backendapi/service/impl/EndpointServiceImplTest.java
https://issues.apache.org/jira/browse/DATALAB-2130
Added check for TERMINATED status in EndpointServiceImpl.removeEndpointInAllProjects(). Added unit tests.
=> [DATALAB-2130] Fixed double terminating for edge node during endpoint disconnection

infrastructure-provisioning/src/general/files/aws/base_Dockerfile, infrastructure-provisioning/src/general/files/azure/base_Dockerfile
specified qtconsole version in base dockerfile for azure and aws
=> [DATALAB-2168]: SSN deployment fails on step if downloading qtconsole

services/datalab-model/src/main/java/com/epam/datalab/dto/base/DataEngineType.java, services/provisioning-service/src/main/java/com/epam/datalab/backendapi/core/response/handlers/ResourcesStatusCallbackHandler.java, services/self-service/src/main/java/com/epam/datalab/backendapi/schedulers/CheckInfrastructureStatusScheduler.java
Added list of clusters instances to process status sync
=> [DATALAB-2152] -- added cluster instances to scheduler status sync

infrastructure-provisioning/src/general/lib/azure/actions_lib.py, infrastructure-provisioning/src/general/lib/azure/meta_lib.py, infrastructure-provisioning/src/general/scripts/azure/ssn_prepare.py
commented self.authorization_client in azure meta and actions lib
=> [DATALAB-2173]: [Azure]: SSN deployment fails

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
changed some apt dependencies during ensure_r step
=> [DATALAB-2189]: Notebook creation fails on stage of 'devtools' installation

infrastructure-provisioning/src/dataengine/scripts/configure_dataengine.py, infrastructure-provisioning/src/general/conf/datalab.ini, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/jupyter/scripts/configure_jupyter_node.py, infrastructure-provisioning/src/jupyterlab/scripts/configure_jupyterlab_node.py, infrastructure-provisioning/src/rstudio/scripts/configure_rstudio_node.py, infrastructure-provisioning/src/tensor-rstudio/scripts/configure_tensor-rstudio_node.py, infrastructure-provisioning/src/zeppelin/scripts/configure_zeppelin_node.py
fixed Notebook creation fails on stage of 'IRkernel' installation
=> [DATALAB-2190]: Notebook creation fails on stage of 'IRkernel' installation

infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py
added libgit2-dev  installation before devtools installation
=> [DATALAB-2226]: fixed Library from R package is not installed on Dataproc

infrastructure-provisioning/src/general/conf/datalab.ini, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
changed cntk version for python2 and how cntk is installed
=> [DATALAB-2221]: DeepLearning creation fails on stage of CNTK instalation

infrastructure-provisioning/src/dataengine/scripts/configure_dataengine.py, infrastructure-provisioning/src/general/conf/datalab.ini, infrastructure-provisioning/src/jupyter/scripts/configure_jupyter_node.py, infrastructure-provisioning/src/jupyterlab/scripts/configure_jupyterlab_node.py, infrastructure-provisioning/src/rstudio/scripts/configure_rstudio_node.py, infrastructure-provisioning/src/tensor-rstudio/scripts/configure_tensor-rstudio_node.py, infrastructure-provisioning/src/zeppelin/scripts/configure_zeppelin_node.py
specified pbdZMQ version for R 3.4.4
=> [DATALAB-2286]: fixed Jupyter/RStudio/Zeppelin/TensorFlow/JupyterLab/Data engine creation fails 

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py
added handling of apt and dpkg locks
=> [DATALAB-1527]: fixed Rarely notebook/ssn are not created successful from the first attempt

infrastructure-provisioning/src/general/scripts/gcp/project_prepare.py, infrastructure-provisioning/terraform/bin/deploy/endpoint_fab.py
=> [DATALAB-2310]: fixed [GCP]: Project creation fails on external endpoint

infrastructure-provisioning/src/general/lib/os/debian/common_lib.py
added handling of lock during apt update
=> [DATALAB-1527]: Rarely notebook/ssn are not created successful from the first attempt	

infrastructure-provisioning/src/general/files/aws/base_Dockerfile, infrastructure-provisioning/src/general/files/azure/base_Dockerfile, infrastructure-provisioning/src/general/files/gcp/base_Dockerfile
specified decorator previous stable version
=> [DATALAB-2345]: SSN creation fails on dowloading decorator-5.0.2.tar.gz

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
=> [DATALAB-2091]: fixed Jupyter creation fails on stage of roxygen2 package installatoin

infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/lib/os/debian/edge_lib.py
added retries for luarocks rocks installation in case of download error
=> [DATALAB-2361]: fixed Sometimes project creation fails on stage of luarocks installation

infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/scripts/aws/edge_configure_route_table.py, infrastructure-provisioning/src/general/scripts/aws/project_prepare.py, infrastructure-provisioning/src/general/scripts/aws/ssn_create_endpoint.py
added tags to project route table necessary for its removal during ssn termination
=> [DATALAB-1724]: fixed project route tables accumulation

infrastructure-provisioning/src/general/lib/aws/actions_lib.py, infrastructure-provisioning/src/general/scripts/aws/project_prepare.py, infrastructure-provisioning/src/general/scripts/aws/project_terminate.py
added project route table removal during project termination
=> [DATALAB-1724]: fixed project route table accumulation

infrastructure-provisioning/src/general/lib/os/debian/edge_lib.py
added warn_only True to luarocks install
=> [DATALAB-2361]: corrected luarocks installation retries

infrastructure-provisioning/src/general/scripts/azure/ssn_terminate.py
added check if  resources have tag with key "SBN" before comparing service_base_name with "SBN" tag value
=> [DATALAB-2340]: Azure fixed SSN termination fails

infrastructure-provisioning/scripts/deploy_datalab.py, infrastructure-provisioning/src/general/conf/datalab.ini, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/ssn/scripts/configure_ui.py
added jars download instead of build
=> [DATALAB-2386]: fixed SSN deployment fails

services/self-service/src/main/resources/webapp/src/app/resources/exploratory/install-libraries/install-libraries.component.ts
Reverts apache/incubator-datalab#1155
=> Revert "[DATALAB-2383] removed Close button for Library installation error"

infrastructure-provisioning/src/general/files/aws/dataengine-service_description.json
added emr version 6.2 with spark 3 in templates
=> [DATALAB-2268]: Updated EMR version

infrastructure-provisioning/terraform/bin/deploy/endpoint_fab.py
added dynamic definition of docker-ce version
=> [DATALAB-2411]: fixed Endpoint creation fails

infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/gcp/dataengine-service_install_libs.py, infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py
fixed additional lib installation for gcp dataengine-service
=> [DATALAB-2429]: fixed Library installation fails

infrastructure-provisioning/src/general/lib/os/fab.py
fixed R package install for spark
=> [DATALAB-2499]: fixed Any library is not installed for Apache Standalone cluster

infrastructure-provisioning/src/general/scripts/os/get_list_available_pkgs.py, infrastructure-provisioning/src/general/scripts/os/install_additional_libs.py
commented unused lines for pip2
=> [DATALAB-2513]: commented pip2 package in code

infrastructure-provisioning/src/general/lib/os/redhat/notebook_lib.py, infrastructure-provisioning/src/general/scripts/aws/dataengine-service_install_libs.py
fixed emr yum and pip packages install errors
=> [DATALAB-2515]: fixed It is impossible to install library

infrastructure-provisioning/src/general/lib/os/fab.py
=> [DATALAB-2508] - Possible reason of error "connection reset by peer" fixed

infrastructure-provisioning/src/general/lib/azure/actions_lib.py
fixed inability to cp/mv files due to wrong disk mount path
=> [DATALAB-1837]: fixed The second (via image) Jupyter creation fails

services/datalab-webapp-common/src/main/java/com/epam/datalab/properties/ChangePropertiesConst.java, services/datalab-webapp-common/src/main/java/com/epam/datalab/properties/ChangePropertiesService.java
- regexps are adjustment
- special symbols filter
=> [DATALAB-2370] Empty config lines adjustment

infrastructure-provisioning/src/general/templates/os/py3spark_local_template.json
[DATALAB-1866]: Added path of virtual environment's python to PATH
=> [DATALAB-1866]: Added path of virtual environment's python to PATH

infrastructure-provisioning/scripts/deploy_repository/deploy_repository.py, infrastructure-provisioning/src/general/conf/datalab.ini, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/templates/azure/interpreter_spark.json, infrastructure-provisioning/src/zeppelin/scripts/configure_zeppelin_node.py
Using built from sources custom Zeppelin
=> [DATALAB-2542]: Custom Zeppelin

infrastructure-provisioning/src/general/lib/os/fab.py
=> [DATALAB-2544]: Jupyter virtual environment fixes

infrastructure-provisioning/src/general/files/aws/zeppelin_description.json, infrastructure-provisioning/src/general/files/azure/zeppelin_description.json, infrastructure-provisioning/src/general/files/gcp/zeppelin_description.json
[DATALAB-2585]: Fixed zeppelin version in UI to 0.9.1
=> [DATALAB-2585]: Fixed zeppelin version in UI

infrastructure-provisioning/src/zeppelin/templates/zeppelin-notebook.service
[DATALAB-2583]: Zeppelin service restart
=> [DATALAB-2583]: Zeppelin service restart

infrastructure-provisioning/src/dataengine/scripts/configure_dataengine.py, infrastructure-provisioning/src/deeplearning/scripts/configure_deep_learning_node.py, infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py, infrastructure-provisioning/src/general/lib/os/fab.py, infrastructure-provisioning/src/general/scripts/azure/dataengine_prepare.py, infrastructure-provisioning/src/general/scripts/os/common_clean_instance.py, infrastructure-provisioning/src/general/scripts/os/deeplearning_install_dataengine_kernels.py
Deeplearning notebook configuration(with conf_deeplearning_cloud_ami=true) and cluster creation fixed.
=> [DATALAB-2555]: Deeplearning spark cluster creation fixed

infrastructure-provisioning/src/general/lib/aws/meta_lib.py
aws instance status is checked only if instance id is present
=> [DATALAB-2595]: fixed edge status docker error

services/self-service/src/main/resources/webapp/src/app/administration/project/project-list/project-list.component.html
commented "recreate edge node" button
=> prevented recreate edge node from web UI

services/self-service/src/main/resources/webapp/src/app/administration/project/project-list/project-list.component.html, services/self-service/src/main/resources/webapp/src/assets/styles/_dialogs.scss
also restored "Recreate edge node" button
=> [Datalab 2575]: fixed link alignment

services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/BillingServiceImpl.java
the string value is changed to null
=> [DATALAB-2556] Null value of the Compute resource

services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/ProjectServiceImpl.java
Before project creation, the budget quota is validated
=> [DATALAB-2488] Project quota validation

infrastructure-provisioning/src/general/scripts/azure/jupyterlab_configure.py, infrastructure-provisioning/src/ssn/files/azure/mongo_roles.json, services/self-service/src/main/resources/mongo/azure/mongo_roles.json
[DATALAB-2626]: JupyterLab was added to the supported notebook templates list on Azure
=> [DATALAB-2626]: JupyterLab was added to the Azure

infrastructure-provisioning/src/general/files/aws/tensor-jupyterlab_description.json
[DATALAB-2718] Changed config for tensor with jupyterlab template
=> [DATALAB-2718] Support only two shapes for instance creation

infrastructure-provisioning/src/general/files/azure/base_Dockerfile, infrastructure-provisioning/src/general/scripts/azure/edge_configure.py, infrastructure-provisioning/src/general/scripts/azure/edge_prepare.py, infrastructure-provisioning/src/general/scripts/azure/edge_terminate.py, infrastructure-provisioning/src/general/scripts/azure/project_prepare.py, infrastructure-provisioning/src/general/scripts/azure/ssn_configure.py, infrastructure-provisioning/src/general/scripts/azure/ssn_prepare.py, infrastructure-provisioning/src/general/scripts/azure/ssn_terminate.py
[DATALAB-2731]: Removed the ability to delete data lake directory
=> [DATALAB-2731]: Fixed an issue with creating an SSN

pom.xml, services/billing-azure/pom.xml, services/datalab-webapp-common/pom.xml, services/provisioning-service/pom.xml, services/self-service/pom.xml
Reverts apache/incubator-datalab#1467
=> Revert "[DATALAB-2738]: update libs versions "

pom.xml, services/billing-azure/pom.xml, services/datalab-webapp-common/pom.xml, services/provisioning-service/pom.xml, services/self-service/pom.xml
This reverts commit f10a0eb5c6ebaea228ca607820aeded367046f3f, reversing
changes made to ffea61bd40e411e596fe64637468c25d8bd76bc6.
=> [DATALAB-2738] reverting because of nexus issues

infrastructure-provisioning/src/base/scripts/install_prerequisites.py
[DATALAB-2746]: Changed libs in install_prerequisites.py file
=> [DATALAB-2746]: Fixed issue with depricate library

services/self-service/src/main/java/com/epam/datalab/backendapi/dao/AuditDAO.java, services/self-service/src/main/java/com/epam/datalab/backendapi/dao/AuditDAOImpl.java, services/self-service/src/main/java/com/epam/datalab/backendapi/domain/AuditReportLine.java, services/self-service/src/main/java/com/epam/datalab/backendapi/resources/AuditResource.java, services/self-service/src/main/java/com/epam/datalab/backendapi/resources/dto/AuditFilter.java, services/self-service/src/main/java/com/epam/datalab/backendapi/service/AuditService.java, services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/AuditServiceImpl.java, services/self-service/src/main/java/com/epam/datalab/backendapi/util/AuditUtils.java, services/self-service/src/test/java/com/epam/datalab/backendapi/resources/AuditResourceTest.java, services/self-service/src/test/java/com/epam/datalab/backendapi/service/impl/AuditServiceImplTest.java
- The audit report is exported to CSV file
=> [DATALAB-2245] Export Audit report

services/self-service/src/main/resources/webapp/src/app/resources/resources-grid/resources-grid.component.html
Disabled cluster creation for tensor-jupyterlab template
=> [DATALAB-2756]: disabled compute for tensor-jupyterlab template

infrastructure-provisioning/src/general/lib/azure/actions_lib.py, infrastructure-provisioning/src/general/scripts/azure/common_create_instance.py
=> [DATALAB-2731]: Disallowed network access for managed disks

infrastructure-provisioning/src/general/lib/os/debian/notebook_lib.py
=> [DATALAB-2795]: Jupyter 502, nbformat

services/self-service/src/main/java/com/epam/datalab/backendapi/domain/AuditReport.java, services/self-service/src/main/java/com/epam/datalab/backendapi/resources/AuditResource.java, services/self-service/src/main/java/com/epam/datalab/backendapi/service/AuditService.java, services/self-service/src/main/java/com/epam/datalab/backendapi/service/impl/AuditServiceImpl.java, services/self-service/src/test/java/com/epam/datalab/backendapi/service/impl/AuditServiceImplTest.java
- auditresource, auditreport objects have been added
=> [DATALAB-1953] AuditReport with header 

infrastructure-provisioning/src/general/conf/datalab.ini
=> [DATALAB-2813]: AWS Deeplearning

infrastructure-provisioning/src/general/scripts/aws/common_prepare_notebook.py
[DATALAB-2848]: Added notebook creation fails on the custom image absence
=> Datalab 2848

infrastructure-provisioning/scripts/deploy_datalab.py
Reverts apache/incubator-datalab#1809
=> Revert "[DATALAB-3109]: Disable check-in keys for AWS"
